
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - producao
      - qualidade
      - pecas
      - relatorios

  producao:
    build: ./producao
    ports:
      - "5001:5000"

  qualidade:
    build: ./qualidade
    ports:
      - "5002:5000"

  pecas:
    build: ./pecas
    ports:
      - "5003:5000"

  relatorios:
    build: ./relatorios
    ports:
      - "5004:5000"

  certificadora:
    build: ./certificadora
    ports:
      - "5005:5000"
